/**
 * Simulates uploading an image to a Google Cloud Storage bucket.
 * In a real frontend application, this would require a signed URL generated by a backend
 * to securely upload directly to GCS without exposing credentials.
 */
export const uploadToHazardBucket = async (base64Data: string, mimeType: string): Promise<string> => {
  console.log(`[Storage Service] Initiating upload to bucket: 'hazardimages'`);
  console.log(`[Storage Service] File type: ${mimeType}, Size: ~${Math.round(base64Data.length * 0.75 / 1024)} KB`);
  
  // Simulate network delay for upload
  return new Promise((resolve) => {
    setTimeout(() => {
      const mockUrl = `https://storage.googleapis.com/hazardimages/mock_${Date.now()}.jpg`;
      console.log(`[Storage Service] Upload complete. Mock URL: ${mockUrl}`);
      resolve(mockUrl);
    }, 1500);
  });
};
